title: RideFlips 
author: Anyona
email: anyonazadocc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We do more than just display car pics. We enjoy the true art of our rides.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ZaccFlips # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
